/**
 * verify-engine.cjs — the gate a version bump must pass.
 *
 * The convention (plans/engine-speed-2026-08.md): engine versions and model
 * revisions are PINS (tag+sha256 in assistant-sidecar.cjs's ENGINE object,
 * repo+revision+sha256 in assistant.cjs's MODEL_REGISTRY); every tuned flag
 * lives beside its pin; and this script is what says a new pin is safe.
 * Bump the pin, run this, read the printed deltas. It fails loudly on the
 * regression classes we have actually seen:
 *
 *   1. TERMINATION — a grammar run that pads to its n_predict cap
 *      (measured on b10298: a 36-token answer became 512 tokens of
 *      newlines until the stop trigger shipped). Every call must stop
 *      short of its cap.
 *   2. CONSTRAINT — every answer must parse as JSON; a schema that stops
 *      constraining is a silent quality hole.
 *   3. COMPACTNESS — the sidecar's autogenerated compact grammar must
 *      actually engage: its token counts stay at or below the host's
 *      pretty-grammar counts. A bump that quietly loses the compact path
 *      pays ~1/3 more decode tokens on every call.
 *   4. SPEED FLOOR — sidecar mean latency stays within 1.25x of the
 *      in-process host on the same requests. Catches gross kernel or flag
 *      regressions, deliberately loose so machine noise does not flake.
 *
 * Run: npm run verify:engine
 *      (models must be on disk; ~2 minutes on the fixed request set)
 */
const { app, BrowserWindow } = require('electron');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

app.setName('Latent Write');
const ROOT = path.join(__dirname, '..');
const NODE = '/opt/homebrew/bin/node';
const TSX = path.join(ROOT, 'node_modules', 'tsx', 'dist', 'cli.mjs');
const assistant = require(path.join(ROOT, 'electron', 'assistant.cjs'));
const sidecarModule = require(path.join(ROOT, 'electron', 'assistant-sidecar.cjs'));

let pass = 0, fail = 0;
const gate = (ok, label, detail = '') => {
  if (ok) { pass++; console.log(`  ok   ${label}`); }
  else { fail++; console.log(`  FAIL ${label}${detail ? `\n         ${detail}` : ''}`); }
};

let win = null;
const callBridge = (method, arg) => {
  const payload = JSON.stringify(arg === undefined ? null : arg);
  return win.webContents.executeJavaScript(
    `window.electronAPI.${method}(${payload === 'null' ? '' : payload})`, true,
  );
};

async function main() {
  assistant.registerAssistant();
  win = new BrowserWindow({
    show: false, width: 480, height: 320,
    webPreferences: {
      nodeIntegration: false, contextIsolation: true, sandbox: true,
      preload: path.join(ROOT, 'electron', 'preload.cjs'),
    },
  });
  await win.loadURL('about:blank');

  console.log(`engine binary: ${sidecarModule.binaryPath() || '(absent — will fall back in-process)'}\n`);

  // The fixed request set: real dossier bytes from COMMITTED corpus books,
  // through the shipped module — never hand-rolled prompts.
  const prep = JSON.parse(execFileSync(NODE, [
    TSX, path.join('scripts', 'bench-dossier-prep.ts'), 'anne:Marilla', 'sherlock:Holmes',
  ], { cwd: ROOT, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 }).trim().split('\n').pop());

  const requests = [];
  for (const c of prep) {
    for (const f of ['appearance', 'personality', 'background']) {
      const ask = c.deepFields[f] && c.deepFields[f].ask;
      if (ask) requests.push({ label: `${c.spec}/${f}`, req: ask });
    }
  }
  console.log(`${requests.length} fixed requests\n`);

  const runOne = async (item, mode) => {
    const t0 = Date.now();
    const res = await callBridge('assistantRun', {
      requestId: `ve-${mode}-${item.label}`.replace(/[^a-z0-9-]/gi, '-'),
      task: 'character-dossier', tier: 'max', noThink: false,
      systemPrompt: item.req.systemPrompt, userText: item.req.userText,
      schema: item.req.schema, maxTokens: item.req.maxTokens,
      timeoutMs: 180000, contextSize: 4096,
      ...(mode === 'sidecar' ? { lane: 'batch', jsonStyle: 'compact' } : {}),
    });
    return { res, ms: Date.now() - t0 };
  };

  const rows = [];
  for (const mode of ['host', 'sidecar']) {
    for (const item of requests) {
      const { res, ms } = await runOne(item, mode);
      rows.push({ label: item.label, mode, ms, ok: !!(res && res.ok),
        tokens: (res && res.timings && res.timings.tokens) || 0,
        cap: item.req.maxTokens,
        parsed: !!(res && res.json && typeof res.json === 'object') });
    }
  }

  console.log(`${'request'.padEnd(32)} ${'host ms'.padStart(8)} ${'side ms'.padStart(8)} ${'host tok'.padStart(8)} ${'side tok'.padStart(8)}`);
  for (const item of requests) {
    const h = rows.find((r) => r.label === item.label && r.mode === 'host');
    const s = rows.find((r) => r.label === item.label && r.mode === 'sidecar');
    console.log(`${item.label.padEnd(32)} ${String(h.ms).padStart(8)} ${String(s.ms).padStart(8)} ${String(h.tokens).padStart(8)} ${String(s.tokens).padStart(8)}`);
  }
  console.log('');

  const sidecarEngaged = (await callBridge('assistantStatus', { tier: 'max' })).sidecar.alive;
  gate(rows.every((r) => r.ok && r.parsed), 'CONSTRAINT: every answer ok and JSON-parsed',
    rows.filter((r) => !r.ok || !r.parsed).map((r) => `${r.mode}:${r.label}`).join(', '));
  gate(rows.every((r) => r.tokens > 0 && r.tokens < r.cap - 8),
    'TERMINATION: every call stopped short of its cap',
    rows.filter((r) => !(r.tokens > 0 && r.tokens < r.cap - 8)).map((r) => `${r.mode}:${r.label}=${r.tokens}/${r.cap}`).join(', '));
  if (sidecarEngaged) {
    const tokPairs = requests.map((item) => ({
      h: rows.find((r) => r.label === item.label && r.mode === 'host').tokens,
      s: rows.find((r) => r.label === item.label && r.mode === 'sidecar').tokens,
    }));
    gate(tokPairs.every((p) => p.s <= p.h * 1.15 + 4),
      'COMPACTNESS: sidecar token counts at or below the host pretty counts',
      tokPairs.map((p) => `${p.s}/${p.h}`).join(' '));
    const mean = (mode) => {
      const xs = rows.filter((r) => r.mode === mode && r.ok).map((r) => r.ms);
      return xs.reduce((a, b) => a + b, 0) / Math.max(1, xs.length);
    };
    gate(mean('sidecar') <= mean('host') * 1.25,
      `SPEED FLOOR: sidecar mean ${Math.round(mean('sidecar'))}ms within 1.25x of host ${Math.round(mean('host'))}ms`);
  } else {
    console.log('  (sidecar absent on this machine — fallback path verified, engine gates skipped)');
  }

  console.log(`\n${fail === 0 ? 'PASS' : 'FAIL'} — ${pass} passed, ${fail} failed\n`);
  app.exit(fail === 0 ? 0 : 1);
}

app.whenReady().then(main).catch((e) => { console.error(e); app.exit(1); });
